version: "3.8"

services:
  db:
    container_name: "BSA-postgres"
    image: postgres:15.3-alpine3.18
    hostname: "BSA"
    volumes:
      - ./postgresql/data:/vap/lib/postgresql/data
    env_file:
      - ".env"

  api:
    container_name: "BSA-api"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ".env"
    command: "python -m api"
    volumes:
      - ".:/opt"
    depends_on:
      - db

  auth:
    container_name: "BSA-auth"
    build:
      context: .
      dockerfile: Dockerfile
    command: "python -m auth"
    env_file:
      - ".env"
    volumes:
      - "./auth:/opt/auth:rw"
      - "./src:/opt/src:rw"
    depends_on:
      - db

  nginx:
    container_name: "BSA-nginx"
    image: nginx:1.25-alpine3.18
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./conf.d:/etc/nginx/conf.d"
      - "./log:/var/log/nginx"
    depends_on:
      - db
      - api
      - auth
